### ISSUE TITLE
Mird term report review 

### ISSUE THREAD

**Issue by amanjain454** [muralits98/Predicting-Wild-Fire-with-Weather-Data-in-the-US-Geography#5]
The team is using weather parameters like pressure, temperature, humidity, etc to predict wildfires. 

Three things you like about the report, 
	1. It's very clean, detailed and well flow. 
	2. The team looked to have to spend a lot of time in frontloading the project - trying out various models at an early stage. This will help in trying out new things in the second half. 
	3. Interesting technique to avoid over-fitting. TIL (Today I Learnt) moment for me. 
	
Three areas for improvement (at least one sentence each). 
	1. I did not understand the meaning of "We used precision and recall metrics to form the dataset" in abstract and in images. Some context of problems being faced would have helped. 
	2. 100km look too wide in general (it might be ok in the context of the given dataset). Alternatively, you can also explore google API to get city polygons. (https://developers.google.com/maps/documentation/geocoding/intro). Then we could use some of the algorithms like this (https://gis.stackexchange.com/questions/133625/checking-if-points-fall-within-polygon-shapefile) to work out if lat long falls in a polygon or not. 
	3. Does one fire affect only one city? Or multiple cities? Some insights about available features in the dataset would have helped.

**Comment by muralits98** [comment]
@amanjain454 Thank you for your comments especially the polygon idea! We'll look into trying this.
The statement "We used precision and recall metrics to form the dataset" refers to the fact that we tried understanding how many positive and negative examples are needed to ensure bias-variance trade-off. So, we identified that an equal number of positive & negative examples created that tradeoff in our case. But, to show you what actually happened to those metrics when the number of positive was kept at a fixed number, 1400 in our case, the graphs show how the precision and recall changed with the addition of 10 negative examples. What's interesting is to really see how many negative samples it took to cause a shift in the recall metric, while the precision went lower and lower.

Why do this? Because our dataset has roughly 35k positive and 1M negative, overall. 

Why do you want trade-off? We are actually venturing into this to see if we can actually compromise on precision because recall does not seem to change much.

3 is very interesting. We should see how fires co-relate. This is something we did not look into because of the struggle to deal with data imbalance. Thanks for bringing this up.

We also hope you got a chance to see the visualization on the website mentioned. I noticed it's not clickable so it's actually on the front page of the repo.

Overall,
What we understand is from your comments is to:
1. Show the dataset.
2. Show the EDA notebook (As messy as the data Haha!)

Thank you!
